events {}

http {
    # LOAD BALANCING (optionnel)
    upstream auth_service {
        server auth-service:8082;

    }

    server {
        listen 80;

        # CORS (Angular)
        add_header Access-Control-Allow-Origin * always;
        add_header Access-Control-Allow-Methods * always;
        add_header Access-Control-Allow-Headers * always;

        if ($request_method = OPTIONS) {
            return 204;
        }

        # AUTH ROUTES

        location /api/auth/ {

            proxy_pass http://auth_service/;

            # JWT forwarding
            proxy_set_header Authorization $http_authorization;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}